name: forensicvision
channels:
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.12.1
      - click==8.3.1
      - contourpy==1.3.2
      - exceptiongroup==1.3.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.1
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - shellingham==1.5.4
      - simsimd==6.5.12
      - stringzilla==4.6.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==1.0.24
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
